### ISSUE TITLE
Shuttles - iPhone Shuttles icons Dance

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#679] opened 2015-01-07 22:56 UTC
At certain times (I don't know how they are calculated) the bus location has not changed but the pin does a little dance.  It looks like the bus pin is being reset to its default position then being set to the correct position and animating this change.

**Comment by justinanderson** [comment] 2015-01-16 06:38
Not able to reproduce anymore. Closing. :+1:

**Closed by justinanderson** 2015-01-16 06:38 UTC
Labels: low, pending review
