### ISSUE TITLE
Shuttles - iPhone - Floating Pins when going from Route/Stop View to Full Screen Map - Sporadic

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#713] opened 2015-01-12 15:39 UTC
When going from route with map and stops view to full screen map the pins float and make the module not usable.

**This happens sporadically.  Cannot find a definite way to reproduce**

![screen shot 2015-01-12 at 10 35 23 am](https://cloud.githubusercontent.com/assets/1474560/5705375/dd180322-9a46-11e4-8af1-15a14daf24bc.png)

**Comment by LoganWright** [comment] 2015-01-19 15:09
@Smartcop - I can't seem to recreate this, do you have any hints as to what you did to get this so I can try and find a way to replicate it consistently?

**Comment by justinanderson** [comment] 2015-01-19 15:19
@LoganWright I haven't seen it myself since the latest async shuttles changes were made, so my guess is that it was happening when a model update finished in the middle of the map transitioning from compact to fullscreen.

I'm going to close this as can't reproduce.

**Closed by justinanderson** 2015-01-19 15:19 UTC
Labels: medium
